### ISSUE TITLE
[Back-end] Users Model

### ISSUE THREAD

**Issue by Marsnaut** [Shade-Heart/graceshopper#4]
Users
    Users must have a valid email address
    Users email must be unique

**Comment by paolaneira** [comment]
HD - coder 
PN - reviewer

**Comment by paolaneira** [comment]
Add a isAdmin column with a BOOLEAN and change the file name to "users.js"

**Comment by paolaneira** [comment]
Hello!

Can we please add a "before each" hook for "returns true if the password is correct": in the user model. :)
